### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [neomjs/neomjs-realworld-example-app#3]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by tobiu** [comment]
Hi @geromegrignon,

I adjusted the endpoint (well, this part was easy). I also added all changes from the version inside the main neo repo (both versions are in sync again).

Afterwards I encountered an issue with the latest webpack version, but already added a hotfix.

dev mode:
![Screenshot 2021-11-08 at 16 47 44](https://user-images.githubusercontent.com/1177434/140786422-55dc36ba-880e-40d9-9ae1-d497cabda998.png)

dist/production:
![Screenshot 2021-11-08 at 18 04 21](https://user-images.githubusercontent.com/1177434/140786475-b0e3406a-2948-4dc2-aa29-6aeebcbe91c3.png)

Please open a new ticket, in case there are more API changes which should get adjusted in this implementation.

Best regards,
Tobias

**Comment by geromegrignon** [comment]
Hey @tobiu!

Thanks so much for the changes!
