### ISSUE TITLE
Online demo is not working

### ISSUE THREAD

**Issue by JohanHeyvaert** [neomjs/neomjs-realworld-example-app#5]
Hello,
Just to notify that the online demo seems broken:
![image](https://user-images.githubusercontent.com/13747250/216347289-f51813b2-de9f-49f4-81e1-93c6fb0f25f1.png)

Is this repository still maintained?

Best regards,
Johan

**Comment by tobiu** [comment]
Hi @JohanHeyvaert!

Thanks for the heads up. The deployment of the neo online examples (github pages) is not related to other child repos inside the neomjs namespace yet. This repo still runs on neo v4 and works fine, however the deployed version of the app is this one: https://github.com/neomjs/neo/tree/dev/apps/realworld (neo v5).

I took a dive into it and found 2 separate issues (already fixed locally).

I will push the fixes now and deploy a running version of v5 afterwards.

**Comment by tobiu** [comment]
https://neomjs.github.io/pages/node_modules/neo.mjs/apps/realworld/index.html

<img width="1174" alt="Screenshot 2023-02-02 at 19 51 25" src="https://user-images.githubusercontent.com/1177434/216421899-3777beae-c277-4f2e-a285-30ca18a67c97.png">

**Comment by tobiu** [comment]
soooo: https://github.com/neomjs/neomjs-realworld-example-app/commit/be4936f6bcb723432fe6638edb80cff562b3664d

this repo is now using the latest neo version as well. tested the app locally (dev mode & dist prod), as well as the docs app (dev mode & dist prod).

enjoy ;)

**Comment by JohanHeyvaert** [comment]
Great! Thanks a lot. 😃🚀
